"""Render a GRaSP ``job.toml`` from a schema artifact + a job's overrides.

This is the frozen provenance record: the fully-resolved TOML the daemon hands
to GRaSP. It is produced deterministically so re-rendering the same inputs is
byte-for-byte identical.

How a value is chosen, per field (Contract A + Contract B):

* start from the schema artifact's (per-instrument) resolved default;
* replace it with the Contract B override for that section+field, if present;
* omit fields whose resolved value is ``null`` — GRaSP computes those at runtime
  (TOML has no null to emit anyway);
* skip ``supported: false`` sections entirely (GRaSP falls back to its own
  defaults for them and never runs them; the web never overrides them).

``general.out_dir`` (the job's output dir) and the ``[input]`` block (local temp
paths from the fetcher) are injected — they are never part of a Contract B
document. Section headers are the schema's long canonical keys, which is exactly
what GRaSP's loader (``grasp.input.job``) expects; numeric enums (``value_type:
int``, e.g. ``sgn``) are emitted unquoted, string enums as their canonical value.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .logging_conf import get_logger
from .schema import SchemaArtifact

log = get_logger(__name__)

# Order of the [input] keys, so output is stable and matches GRaSP's fields.
_INPUT_ROLE_ORDER = ("label_file", "science_file", "auxiliary_file")


def render_job_toml(
    artifact: SchemaArtifact,
    overrides: dict[str, dict[str, Any]],
    out_dir: str,
    input_files: dict[str, str | Path],
) -> str:
    """Render the complete ``job.toml`` text for a job.

    Args:
        artifact: the schema artifact for the job's (instrument, product).
        overrides: Contract B ``overrides`` (section -> field -> value); sparse.
        out_dir: the job's output directory, injected as ``general.out_dir``.
        input_files: role -> local path from the fetcher, injected as ``[input]``.
    """
    lines: list[str] = [
        "# GRaSP job file — generated by porpass-daemon; do not edit.",
        f"# schema_version = {artifact.schema_version}, "
        f"grasp_version = {artifact.grasp_version}",
        f"# instrument = {artifact.instrument}, product = {artifact.product}",
        "",
    ]

    general = artifact.section("general")
    if general is None:  # pragma: no cover - every artifact has general
        raise ValueError("schema artifact has no 'general' section")
    lines += _render_general(general, overrides.get("general", {}), out_dir)
    lines += _render_input(input_files)

    # Stages in pipeline order, then the remaining globals — supported only.
    remaining = [
        *artifact.stages,
        *(g for g in artifact.globals if g.get("key") != "general"),
    ]
    for section in remaining:
        if not section.get("supported", True):
            continue
        block = _render_section(section, overrides.get(section["key"], {}))
        if block is not None:
            lines += block

    return "\n".join(lines) + "\n"


def write_job_toml(path: str | Path, content: str) -> Path:
    """Write rendered content to ``path`` and return it."""
    p = Path(path)
    p.write_text(content)
    return p


# --------------------------------------------------------------------------- #
# Section rendering
# --------------------------------------------------------------------------- #

def _render_general(
    section: dict[str, Any], ov: dict[str, Any], out_dir: str
) -> list[str]:
    """Render ``[general]`` — out_dir is always injected; verbose etc. resolve."""
    lines = ["[general]"]
    for field in section["fields"]:
        name = field["name"]
        if name == "out_dir":
            value: Any = out_dir            # injected; authoritative
        elif name in ov:
            value = ov[name]
        else:
            value = field.get("default")
        if value is None:
            continue
        lines.append(f"{name} = {_format_value(field, value)}")
    lines.append("")
    return lines


def _render_input(input_files: dict[str, str | Path]) -> list[str]:
    """Render the injected ``[input]`` block (local temp paths)."""
    lines = ["[input]"]
    for role in _INPUT_ROLE_ORDER:
        if role in input_files:
            lines.append(f"{role} = {_toml_string(str(input_files[role]))}")
    # Any non-standard roles (future instruments) still get emitted, in order.
    for role in sorted(set(input_files) - set(_INPUT_ROLE_ORDER)):
        lines.append(f"{role} = {_toml_string(str(input_files[role]))}")
    lines.append("")
    return lines


def _render_section(section: dict[str, Any], ov: dict[str, Any]) -> list[str] | None:
    """Render one stage/global section, or ``None`` if it has nothing to emit."""
    field_lines: list[str] = []
    for field in section["fields"]:
        name = field["name"]
        value = ov[name] if name in ov else field.get("default")
        if value is None:
            continue
        field_lines.append(f"{name} = {_format_value(field, value)}")
    if not field_lines:
        return None
    return [f"[{section['key']}]", *field_lines, ""]


# --------------------------------------------------------------------------- #
# Value formatting (type-driven for correct, deterministic TOML)
# --------------------------------------------------------------------------- #

def _format_value(field: dict[str, Any], value: Any) -> str:
    """Format a value as TOML according to the field's declared type."""
    ftype = field.get("type")
    value_type = field.get("value_type")

    # bool first — Python bool is a subclass of int.
    if ftype == "bool" or isinstance(value, bool):
        return "true" if value else "false"
    if ftype == "int" or (ftype == "enum" and value_type == "int"):
        return str(int(value))
    if ftype == "float":
        return _format_float(value)
    if ftype == "str" or (ftype == "enum" and value_type == "str"):
        return _toml_string(str(value))

    # Fallback: infer from the Python value (defensive; schema types are known).
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return _format_float(value)
    return _toml_string(str(value))


def _format_float(value: Any) -> str:
    """Deterministic float text that always reads back as a TOML float."""
    f = float(value)
    s = repr(f)
    if not any(c in s for c in (".", "e", "E", "n", "i")):  # nan/inf/exp already ok
        s += ".0"
    return s


def _toml_string(s: str) -> str:
    """Quote a string as a TOML basic string with the required escapes."""
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'
